version: '3.2'
services:
  yireader:
    image: uhziel/yireader:prerelease
    depends_on:
      - db
    restart: always
    environment:
      - NODE_ENV=production
      - SECRET_KEY=Mwxyf3.gwDkMEf
      - MONGODB_URI=mongodb://root:pZXswnYF#ch6iU@db:27017/yireader?authSource=admin&retryWrites=true&w=majority
    ports:
      - 3002:3001

  db:
    image: mongo:4.4-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pZXswnYF#ch6iU
    volumes:
      - ./dbdata:/data/db
